# Generated by Django 4.1.1 on 2022-09-20 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_trained', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('ANDi_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('company_role', models.CharField(choices=[('1', 'Product Developer'), ('2', 'Product Analyst'), ('3', 'Squad Lead'), ('4', 'Cloud Engineer')], max_length=50)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='trainers.club')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.workshop')),
            ],
            options={
                'verbose_name_plural': 'Workshop_Details',
                'unique_together': {('trainer', 'workshop')},
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='trainers',
            field=models.ManyToManyField(blank=True, through='trainers.Workshop_Details', to='trainers.trainer'),
        ),
    ]
