# Generated by Django 4.1.1 on 2022-09-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_rename_name_workshop_details_workshop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_details',
            name='experience_level',
            field=models.CharField(choices=[('0', '0 - No experience'), ('1', '1 - Shadowing'), ('2', '2 - Co-run a workshop'), ('3', '3 - Lead a workshop with support'), ('4', '4 - Lead workshop independently'), ('5', '5 - Trains others to run workshops')], max_length=50),
        ),
    ]
