# Generated by Django 4.1.1 on 2022-09-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_trainer_img_alter_trainer_company_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='company_role',
            field=models.CharField(choices=[('Product Developer', 'Product Developer'), ('Product Analyst', 'Product Analyst'), ('Squad Lead', 'Squad Lead'), ('Cloud Engineer', 'Cloud Engineer'), ('Onboarding Coordinator', 'Onboarding Coordinator'), ('Principal Consultant', 'Principal Consultant')], max_length=50),
        ),
    ]
